### ISSUE TITLE
Issues with running files

### ISSUE THREAD

**Issue by Chaprnks** [shovon668/cfst_nextdns#1]
![jEIYU5g](https://user-images.githubusercontent.com/6340970/170768991-cddf066a-41e0-40bf-a16c-4c0a3288c441.png)

```
# XIU2/CloudflareSpeedTest v2.0.3

2022/05/27 14:21:24 open ip.txt: The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\chapr\Desktop\cfst_nextdns\update.py", line 78, in <module>
    f = open("result.csv", "r", encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: 'result.csv'
```

**Comment by ajshovon** [comment]
Extract everything from CloudflareSpeedTest windows release, not just the exe. Make sure the ip.txt file is extracted properly.

**Comment by Chaprnks** [comment]
I just realized I extracted CloudflareSpeedTest to its own directory (under Program Files) & added to PATH variable. I extracted the CloudflareSpeedTest to the same directory as cfst_nextdns & it works great now. Thank you! 😁

**Comment by ajshovon** [comment]
Closing the issue as it is resolved...
